name: Go

on:
  push:
    paths:
      - "**.go"
  pull_request:
    paths:
      - "**.go"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.0

      - name: Build
        run: go build -v ./cmd/...

      - name: Tests
        run: go test -v ./...
